import type { Metadata } from "next";
import { Inter, Lato, Work_Sans } from "next/font/google";
import localFont from "@next/font/local";
import NavBar from "../components/Nav/NavBar";

import { ThemeProvider } from "./Providers";
import "./globals.css";
import TransitionWrapper from "@/components/Animation/AnimationWrapper";
const work_sans = localFont({
  src: "../fonts/WorkSans-VariableFont_wght.ttf",
  variable: "--font-work-sans",
});

const cabin = localFont({
  src: "../fonts/Cabin-VariableFont_wdth,wght.ttf",
  variable: "--font-cabin",
});
const monserrat = localFont({
  src: "../fonts/Montserrat-VariableFont_wght.ttf",
  variable: "--font-monserrat",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cabin.variable + " flex min-h-screen flex-col bg-background"}
      >
        <ThemeProvider>
          <NavBar />
          <main className="h-full">{children}</main>
        </ThemeProvider>
      </body>
    </html>
  );
}
